### ISSUE TITLE
Is it licon or mcon?

### ISSUE THREAD

**Issue by AngeloJacobo** [nickson-jose/OpenLane#1]
Hi, very nice tutorial here, very easy to follow and very informative too. I'm just wondering on the documentation if the blue checkered below is really `licon`? I thought it will be `mcon` since that is the connection between locali and metal1.  I used `what` command and it was described as `viali` (is `viali` just same as `mcon`?). Thanks

![image](https://user-images.githubusercontent.com/87559347/188251588-83a9a1a7-3749-48ff-9b0f-67fc8ca2ba70.png)

**Comment by nickson-jose** [comment]
Hi Angelo

You are right. its `mcon` .
I believe in the earlier release of pdk, we were missing this clarity. Below link should help:

https://skywater-pdk.readthedocs.io/en/main/rules/layers.html?highlight=mcon
